### ISSUE TITLE
Roadmap?

### ISSUE THREAD

**Issue by ashalkhakov** [RyanTKing/wombats#1]
I'm interested in working on this.

Could you tell me some ideas of what you want to do, and some tasks that you need done? Then we could work out a plan and a schedule for implementation.

**Comment by ryantking** [comment]
Thanks for your interest!

This is a passion project for me that I plan on putting more work into after school gets a bit lighter. One of the hardest parts of learning ATS in my opinion is learning the nuances of patsopts and patscc. I am looking to create something similar to Clojure's Leiningen, the Go utility, or Rust's Cargo for ATS.

It started off as a Python script that I was working on to automate making/testing small ATS, which I just put up [here](https://gist.github.com/RyanTKing/aa0405d2ea7a052c0546feccf195b855), then I realized it was probably something the entire ATS community could benefit from.

I would say this this is my tentative development steps:

1. Develop a simple grammar for the config file. I'm currently debating the pros and cons of a JSON syntax versus a INI syntax. Would love to hear your thoughts on this. I'm leaning towards the INI-like syntax just because of it's simplicity.
2. Develop a parser that can turn all the configuration options into a data structure, most likely a record.
3. Create wrappers for all the system commands such as interacting with NPM, patsopt, and pastcc
4. Create a parser for the output from the above commands so I have complete control over what messages get outputted.
5. Add support for multiple project types (normal, atscc2js, atscc2py, etc.)
6. Play around with cutting NPM out of the mix and add support for directly downloading releases of plugins from GitHub (this is way down the line).

I'd love to hear your thoughts and thanks for your interest!

**Comment by ashalkhakov** [comment]
I looked at the script -- very nice! I don't know much Python, though.

I have this issue currently: I'm tired of writing Makefiles for very, very simple programs. Here's an [example](https://github.com/ashalkhakov/ats3d/blob/master/src/TEST/Makefile) of what I'm talking about (note that I'm adding more and more rules like `test01_C_O`). Automating it with a build tool would be nice.

I don't have any experience with Go/Rust/Clojure utilities, but I do have some with .NET Core CLI and Node NPM & WebPack.

Regarding the steps: which features do you intend to add first?

For config file syntax: I don't really mind whatever you choose. One requirement is that it should be easy to generate these files by AST manipulation (e.g. to implement something akin to `npm install` which adds content to the `project.json` file for you).

What I'm also thinking is build automation is a complex task (in general), so we should strive to automate only the most painful parts that have a good algorithmic solution (e.g. package downloading & setting up ATS search path). From what I read about Haskell Cabal, the authors say it turned out to be a very complex piece of software.

**Comment by ashalkhakov** [comment]
I've found this project:

http://xmake.io/

I'm thinking of creating an ATS plugin for it. While I'm at it, I think I'll add some more language plugins! Let us see how that goes.

**Comment by ryantking** [comment]
That looks very very interesting... Why reinvent the wheel!
Haven't used lua since Middle School when I was trying my hand at modding World of Warcraft!

I still think a long-term solution is going to be a build system entirely designed for ATS, but that xmake plugin looks like it could definitely bridge the gap in the mean time!
